apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-ingress
spec:
  tls:
    - secretName: cloudflare
  rules:
    - host: www.yetebaberut.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: react
                port:
                  number: 31000
